# Generated by Django 5.2.7 on 2025-10-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcequeue',
            name='requested_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
