# Generated by Django 5.2.7 on 2025-10-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0003_add_requested_minutes'),
        ('resource_manager', '0003_resourcequeue_requested_minutes'),
    ]

    operations = [
    ]
